# This is a configuration file for the bacon tool
#
# Complete help on configuration: https://dystroy.org/bacon/config/
#
# You may check the current default at
#   https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml

default_job = "nextest"
env.CARGO_TERM_COLOR = "always"

[jobs.check]
command = [
  "cargo",
  "check",
  "--all",
  "--message-format",
  "json-diagnostic-rendered-ansi",
]
need_stdout = true
analyzer = "cargo_json"

[jobs.coverage]
command = ["mise", "coverage"]
need_stdout = true

[jobs.nextest]
command = [
  "cargo",
  "nextest",
  "run",
  "--all",
  "--hide-progress-bar",
  "--failure-output",
  "final"
]
need_stdout = true
analyzer = "nextest"

# If the doc compiles, then it opens in your browser and bacon switches
# to the previous job
[jobs.doc-open]
command = ["cargo", "doc", "--all", "--no-deps", "--open"]
need_stdout = false
on_success = "back"  # so that we don't open the browser at each change

[jobs.bench]
command = [
  "cargo",
  "bench",
  "--bench=converter",
  "--",
  "--color",
  "always",
  "compare",
  "-o",
  "target/benchmarks/converter",
]
allow_warnings = true
need_stdout = true
on_change_strategy = "kill_then_restart"

[keybindings]
b = "job:bench"
