[package]
name = "ottotom"
version = "0.33.0-alpha.1"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/max-te/ottotom"
keywords = ["opentelemetry", "observability", "prometheus", "metrics"]
readme = "README.md"
description = "Conversion of OpenTelemetry metrics to OpenMetrics Text format"

[workspace]
resolver = "3"
members = ["testsupport"]
[workspace.dependencies]
opentelemetry = { version = "0.32.0", default-features = false }
opentelemetry_sdk = { version = "0.32.0", default-features = false, features = [
    "metrics",
] }
ottotom-testsupport = { path = "testsupport", version = "=0.33.0-alpha.1" }

[dependencies]
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
memchr = { version = "2.7.6", optional = true }
itoa = { version = "1.0.15", optional = true }
ryu = { version = "1.0.20" }
tracing = { version = "0.1.41", optional = true }
ufmt = { version = "0.2.0", features = ["std"] }

[features]
exporter = []
tracing = ["dep:tracing"]
experimental = []
fast = ["dep:itoa", "dep:memchr"]
default = ["tracing", "exporter", "fast"]

[dev-dependencies]
ottotom-testsupport.workspace = true
openmetrics-parser = "0.4.4"
tango-bench = "0.7"
insta = { version = "1.43.2" }
divan = { version = "5.0.1", package = "codspeed-divan-compat" }

[[bench]]
name = "converter"
harness = false

[[bench]]
name = "conversion"
harness = false
